include: ../../analysis_options.yaml

analyzer:
  exclude:
    - '**/*.mocks.dart'

linter:
  rules:
    # Disable cascade_invocations for test files - explicit method calls are clearer
    cascade_invocations: false
    # Disable use_named_constants - constructor calls are clearer for testing defaults
    use_named_constants: false
